static QStringList getAllItems() {
    return QStringList() <<
                            "Aal" << "Absinth (45% Vol.)" << "Acai" << "Acerola" << "Ackerbohnen" << "Afa Alge frisch" << "Agavendicksaft" << "Ahornsirup" << "Ajvar" << "Aloe Vera Saft" << "Altbier" << "Amaranth" << "Ananas" << "Ananassaft" << "Anis" <<
                             "Aperol Likör" << "Apfel" << "Apfeldicksaft" << "Apfelessig" << "Apfelkuchen" << "Apfelmus" << "Apfelringe getrocknet" << "Apfelsaft" << "Apfelschorle" << "Apfelwein" << "Appenzeller" << "Aprikose" << "Aronia Beeren" <<
                             "Artischocke" << "Aubergine" << "Auster" << "Austernpilze" << "Avocado" << "Ayran" << "Backfisch" << "Backpulver" << "Bacon" << "Baguette" << "Baiser" << "Balsamico Creme" << "Balsamico Essig" << "Bambussprossen" << "Banane" <<
                             "Bärlauch" << "Barsch" << "Basilikum" << "Basilikum Pesto" << "Basmati Reis roh" << "Bauchspeck" << "Beifuß getrocknet" << "Berberitzen, getrocknet" << "Bergkäse 50% i.Tr." << "Berliner" << "Bier" << "Bier, alkoholfrei" <<
                             "Bierschinken" << "Birne" << "Bismarckhering" << "Blätterteig" << "Blattsalat" << "Blauschimmelkäse" << "Blumenkohl" << "Blutwurst" << "Bockshornklee" << "Bockwurst" << "Bohnenkraut getrocknet" << "Bonbons" << "Borretsch" <<
                             "Brandteig" << "Bratensauce" << "Brathering" << "Bratkartoffeln" << "Bratwurst" << "Brennnessel" << "Brezel" << "Brie" << "Brokkoli" << "Brombeeren" << "Brötchen Weizen" << "Buchweizen" << "Buchweizenmehl" << "Büffelmozzarella"
                             << "Bulgur" << "Bündnerfleisch" << "Butter" << "Butterbrezel" << "Butterkäse" << "Butterkekse" << "Buttermilch" << "Butterpilze" << "Gheebutter" << "Cabanossi" << "Camembert" << "Camu-Camu Pulver" << "Cappuccino" << "Cashewmus"
                             << "Cashewnüsse" << "Cervelatwurst" << "Cevapcici" << "Champagner" << "Champignons" << "Cheddar Käse" << "Cheeseburger" << "Cherrytomaten" << "Chia" << "Chia Brot" << "Chia Brötchen" << "Chicken Nuggets" << "Chicken Wings" <<
                             "Chicorée" << "Chili con carne" << "Chilischote" << "Chinakohl" << "Chlorella" << "Ciabatta Brot" << "Cidre" << "Clementine" << "Cola" << "Cola light" << "Cola Zero" << "Cordon bleu v. Schwein" << "Corned Beef" << "Cornflakes, natur"
                             << "Couscous gekocht" << "Couscous roh" << "Cranberries getrocknet" << "Cranberry" << "Creme fraiche 15%" << "Creme fraiche 30%" << "Crevetten" << "Croissant" << "Curry" << "Currywurst mit Sauce" << "Datteln" <<
                             "Diätbier" << "Dicke Bohnen" << "Diesel" << "Dill" << "Dinkelbrot" << "Dinkelbrötchen" << "Dinkelflocken" << "Dinkelkleie" << "Dinkelmehl, Vollkorn" << "Dinkelnudeln roh" << "Dinkelvollkornbrot" << "Dominosteine" << "Döner" <<
                             "Dönerfleisch" << "Donut" << "Dorade" << "Drachenfrucht" << "Edamer Käse" << "Ei - Vollei" << "Eierkuchen" << "Eierlikör (20% Vol.)" << "Eierpfannkuchen" << "Eiersalat mit Mayonnaise" << "Eierschecke" << "Eigelb" << "Eisbein roh" <<
                             "Eisbergsalat" << "Eiscreme" << "Eiscreme" << "Eiskaffee" << "Eistee" << "Eiweißbrot" << "Eiweißbrötchen" << "Eiweißpulver" << "Eiweiss / Eiklar" << "Eiweißshake mit Milch" << "Emmentaler Käse" << "Endiviensalat" <<
                             "Energydrink" << "Ente" << "Entenbrust" << "Entenleber" << "Erbsensuppe" << "Erdbeeren" << "Erdbeerjoghurt 1.5%" << "Erdbeerkuchen Biskuitteig" << "Erdnüsse" << "Erdnussbutter" << "Erdnussflips" << "Erdnussmus" << "Erdnussöl"
                             << "Erythrit" << "Espresso" << "Essig" << "Essig Öl Dressing" << "Estragon frisch" << "Estragon getrocknet" << "Falafel" << "Fanta Orange" << "Federweißer" << "Feige" << "Feldsalat" << "Fenchel" << "Feta Käse" <<
                             "Fischstäbchen" << "Fladenbrot" << "Flammkuchen" << "Fleischbrühe" << "Fleischkäse" << "Fleischsalat" << "Fleischwurst" << "Flohsamenschalen" << "Flusskrebs" << "Forelle" << "Forelle geräuchert" << "Franzbrötchen" <<
                             "Frikadelle" << "Frischkäse fettreduziert" << "Frischkäse körnig" << "Frischkäse, Doppelrahm" << "Fruchteis / Sorbet" << "Früchtemüsli" << "Früchtetee" << "Fruchtjoghurt 1.5%" << "Fruchtsaft" << "Fruchtzucker" <<
                             "Frühlingsrolle" << "Frühlingszwiebeln" << "Frühlingszwiebel" << "Galiamelone" << "Gambas" << "Gans" << "Gänsebrust" << "Gänsekeule" << "Gänseleberpastete" << "Gänseschmalz" << "Garnelen" << "Geflügelfleischwurst" <<
                             "Geflügelwiener" << "Geflügelwurst" << "Gelatine" << "Gemüsebrühe" << "Gemüsesaft" << "Germknödel" << "Gerstengras Pulver" << "Gerstenmehl, Vollkorn" << "Gewürzgurken" << "Gin (40% Vol.)" << "Glasnudeln roh" << "Glühwein" <<
                             "Gluten, Weizenkleber" << "Gnocchi" << "Goji Beeren getrocknet" << "Gorgonzola" << "Götterspeise gekocht" << "Gouda Käse" << "Granatapfel" << "Grapefruit" << "Grapefruitsaft" << "Grappa (40% Vol.)" << "Graubrot" << "Graupen" <<
                             "griechischer Joghurt 10%" << "Grießbrei" << "Grissinis" << "Grüne Bohnen" << "Grüne Erbsen" << "Grüner Spargel" << "Grüner tee" << "Grünkohl" << "Grützwurst" << "Guacamole" << "Guarkernmehl" << "Guave" << "Gummibärchen" <<
                             "Gurke grün" << "Gyros" << "Hackfleisch gemischt" << "Haferflocken" << "Haferkleie" << "Hafermilch" << "Hagebutten" << "Hagebuttentee" << "Hähnchen" << "Hähnchen gebraten" << "Hähnchenbrust" << "Hähnchenleber" <<
                             "Hähnchenschenkel" << "Hähnchenschnitzel paniert gebraten" << "Halbfettmargarine" << "Halloumi" << "Hamburger" << "Handkäse" << "Hanfmehl" << "Hanfsamen" << "Harzer Käse" << "Hase" << "Haselnüsse" << "Haselnussmilch" <<
                             "Haselnussmus" << "Hefeflocken" << "Hefeteig" << "Hefezopf" << "Heidelbeeren" << "Heilbutt" << "Heiße Schokolade" << "Heringsfilet" << "Himbeeren" << "Hirsch" << "Hirse" << "Hirseflocken" << "Holunder" << "Holundersaft" <<
                             "Honig" << "Honigmelone" << "Hugo Aperitif Cocktail" << "Hühnerfrikassee" << "Hühnersuppe" << "Hummer" << "Hummus" << "Hüttenkäse" << "Ingwer" << "Isomalt" << "Jagdwurst" << "Jägermeister Kräuterlikör" << "Jakobsmuschel" <<
                             "Jasminreis roh" << "Joghurt, 0,1%" << "Joghurt, 1,5%" << "Joghurt, 3.5%" << "Joghurtdressing" << "Joghurteis" << "Johannisbrotkernmehl" << "Kabeljau / Dorsch" << "Kaffee komplett" << "Kaffee mit Milch" << "Kaffee schwarz" <<
                             "Kaffeesahne 10%" << "Kaffeesahne 4%" << "Kaffeesahne 7,5%" << "Kaisergemüse" << "Kaiserschmarrn" << "Kakao, stark entölt" << "Kakaobohnen" << "Kakaobutter" << "Kakaofasern" << "Kakaomilch 1,5%" << "Kakaomilch 3,5%" <<
                             "Kakaopulver gezuckert" << "Kaki" << "Kalbsbries" << "Kalbsfilet" << "Kalbsfleisch" << "Kalbsleber" << "Kalbsleberwurst" << "Kalbsrücken" << "Kalbsschnitzel" << "Kamut" << "Kandiszucker" << "Kaninchen" << "Kapern, Glas" <<
                             "Physalis" << "Karambole" << "Karamel" << "Kardamom gemahlen" << "Karottensaft" << "Karpfen" << "Kartoffeln gekocht" << "Kartoffeln roh" << "Kartoffelbrot" << "Kartoffelchips" << "Kartoffelfasern" << "Kartoffelgratin" <<
                             "Kartoffelpuffer" << "Kartoffelpüree" << "Kartoffelsalat" << "Kartoffelspalten" << "Kartoffelstärke" << "Kartoffelsuppe" << "Käsekuchen" << "Käsespätzle" << "Kasseler" << "Katenschinken" << "Kaugummi" << "Kaviar" << "Kefir" <<
                             "Kekse" << "Kerbel" << "Ketchup" << "Kichererbsen" << "Kichererbsenmehl" << "Kidneybohnen" << "Kiwi" << "Klöße gekocht" << "Knoblauch" << "Knuspermüsli" << "Kochschinken" << "Köfte türkisch" << "Kohlrabi" << "Kohlrübe" <<
                             "Kokosblütenzucker" << "Kokosfett" << "Kokosmehl" << "Kokosmilch" << "Kokosnuss" << "Kokosöl" << "Kokosraspel" << "Kokoswasser" << "Kölsch" << "Konfitüre" << "Konjacnudeln gekocht" << "Konjakmehl" << "Kopfsalat" << "Koriander frisch"
                             << "Koriander gemahlen" << "Körnerbrötchen" << "Kornspitz" << "Krabben" << "Krabbenchips" << "Krakauer Wurst" << "Kräuterbutter" << "Kräuterlikör (30%)" << "Kräuterquark, 40%" << "Kräutertee" << "Krautsalat" << "Kresse"
                             << "Kreuzkümmel" << "Kroketten" << "Kümmel" << "Kümmerling Kräuterlikör" << "Kumquat" << "Kürbis Hokkaido" << "Kürbiskerne" << "Kürbiskernbrötchen" << "Kürbiskernmehl" << "Kürbiskernöl" << "Kurkuma" << "Kuvertüre Vollmilch" <<
                             "Kuvertüre Zartbitter" << "Lachs (Zucht)" << "Lachsforelle" << "Lachsschinken" << "Lactit" << "Lahmacun" << "Lakritze" << "Lammfilet" << "Lammfleisch" << "Lammkeule" << "Lammkotelett" << "Lammrücken" << "Landjäger" <<
                             "Langkornreis roh" << "Languste" << "Lasagne" << "Latte Macchiato" << "Laugenstange" << "Leberkäse" << "Leberknödel" << "Leberwurst" << "Lebkuchen" << "Leinöl" << "Leinsamen" << "Leinsamenbrot" << "Leinsamenmehl teilentölt" <<
                             "Liebstöckel" << "Likör (20% Vol.)" << "Limburger Käse" << "Limette" << "Limonade" << "Limonade light" << "Linsen roh" << "Linsensuppe" << "Linzertorte" << "Litschi" << "Löffelbisquit" << "Lollo Rosso" << "Lorbeer getrocknet"
                             << "Löwenzahn" << "Lyoner" << "Maasdamer Käse" << "Macadamia" << "Mairübchen" << "Mais" << "Maiskolben ganz" << "Maismehl" << "Maisstärke" << "Majoran gerebelt" << "Makrele" << "Makronen" << "Maltit" << "Maltodextrin" <<
                             "Malzbier" << "Mamorkuchen" << "Mandarine" << "Mandeln" << "Mandelmehl" << "Mandelmilch gesüßt" << "Mandelmilch ungesüßt" << "Mandelmus" << "Mango" << "Mangold" << "Maniok" << "Margarine" << "Marmelade" << "Marmorkuchen" <<
                             "Maronen" << "Marzipan" << "Mascarpone" << "Matjes" << "Maulbeeren" << "Maultaschen" << "Mayonnaise" << "Meerrettich" << "Mehrkornbrot" << "Mehrkornbrötchen" << "Mettenden" << "Mie Nudeln" << "Miesmuscheln" << "Milch 0,3%" <<
                             "Milch 1,5%" << "Milch 3,5%" << "Milchbrötchen" << "Milchkaffee" << "Milchpulver" << "Milchreis gekocht" << "Milchschnitte" << "Milchzucker" << "Mineralwasser" << "Mischbrot" << "Mischgemüse" << "Mohn" << "Mohnbrötchen" <<
                             "Möhren / Karotten" << "Molke" << "Morcheln" << "Moringa Pulver" << "Mortadella" << "Mozzarella Käse" << "Multivitaminsaft" << "Mungobohnen" << "Mürbeteig" << "Muskat gemahlen" << "Müsli" << "Müsliriegel" << "Nachos mit Käse"
                             << "Nackensteak Schwein" << "Natron" << "Nektarine" << "Nelken getrocknet" << "Nougat" << "Nudeln gekocht" << "Nudeln, Eierteigware roh" << "Nudeln, Hartweizengrieß roh" << "Nudeln, Vollkorn roh" << "Nudelsalat mit Mayonnaise"
                             << "Nuss Nougat Creme" << "Nussschokolade" << "Nutella" << "Obst, getrocknet" << "Obstbrand/Obstler (45%)" << "Obstsalat" << "Ofenkäse" << "Oliven, grün" << "Oliven, schwarz" << "Olivenöl" << "Omelett" << "Orange" <<
                             "Orangensaft" << "Oregano getrocknet" << "Ouzo (38% Vol.)" << "Pak Choi" << "Pangasius" << "Paniermehl" << "Panko" << "Papaya" << "Paprika, gelb" << "Paprika, grün" << "Paprika, rot" << "Paprikapulver edelsüß" << "Paprikapulver Rosenscharf"
                             << "Paranüsse" << "Parmaschinken fettarm" << "Parmesan Käse" << "Passionsfrucht" << "Pastinaken" << "Pecorino" << "Pekanüsse" << "Peperoni" << "Petersilienwurzel" << "Pfeffer" << "Pfefferbeißer" << "Pfefferminze"
                             << "Pfefferminztee" << "Pferdefleisch" << "Pfifferlinge" << "Pfirsich" << "Pflanzenöl" << "Pflaumen" << "Pflaumen, getrocknet" << "Pflaumenmus" << "Pilsner Bier" << "Pinienkerne" << "Pistazien" << "Pita" << "Pizza" <<
                             "Pizzateig" << "Polenta" << "Pomelo" << "Pommes" << "Popcorn" << "Porree / Lauch" << "Porridge" << "Preiselbeeren" << "Prosecco" << "Puddingpulver Vanille" << "Puderzucker" << "Pumpernickel" << "Putenbrust" << "Putenfleisch" <<
                             "Putenhackfleisch" << "Putenleber" << "Putensalami" << "Putenschnitzel" << "Putensteak" << "Quark, 20%" << "Quark, 40%" << "Quark, Magerquark 0,5%" << "Quinoa" << "Quitte" << "Radicchio" << "Radieschen" << "Radler" <<
                             "Ramazotti Kräuterlikör" << "Rapsöl" << "Ratatouille" << "Räucherlachs" << "Räuchertofu" << "Red Bull" << "Red Bull sugarfree" << "Rehkeule" << "Rehrücken" << "Reis gekocht parboiled" << "Reis roh parboiled" << "Reismehl" <<
                             "Reismilch ungesüßt" << "Reisnudeln roh" << "Reiswaffel" << "Remoulade" << "Rettich" << "Rhabarber" << "Ricotta" << "Rinderbraten" << "Rinderbrühe" << "Rinderfilet" << "Rindergulasch" << "Rinderhackfleisch" << "Rinderhüfte" <<
                             "Rinderleber" << "Rinderroulade" << "Rindersteak" << "Rindertalg" << "Rindertatar" << "Rinderzunge" << "Rindswurst" << "Rippchen" << "Risotto" << "Roastbeef" << "Roggenbrot" << "Roggenbrötchen" << "Roggenknäckebrot" <<
                             "Roggenmehl" << "Roggenmischbrot" << "Roggenvollkornbrot" << "Roggenvollkornmehl" << "Rohrzucker" << "Rollmops" << "Romadur Käse" << "Romanasalat" << "Romanesco" << "Roquefort Käse" << "Rosenkohl" << "Roséwein" << "Rosinen" <<
                             "Rosinenbrötchen" << "Rosmarin" << "Kartoffelrösti" << "Röstzwiebeln" << "Rotbarsch" << "Rote Bete" << "Rote Johannisbeeren" << "rote Linsen roh" << "Rote Zwiebeln" << "Blaukraut" << "Rotwein" << "Rübensaft" << "Rucola" <<
                             "Rührei" << "Rührkuchenteig" << "Rum (37% Vol.)" << "Rum (65% Vol.)" << "Rumkugel" << "Rumpsteak" << "Sahne 10%" << "Sahne 20%" << "Sahne 30%" << "Sahneies" << "Sahnetorte" << "Saibling" << "Salami" << "Salamipizza" << "Salbei getrocknet"
                             << "Salz" << "Salzstangen" << "Sanddorn" << "Sandkuchen" << "Sardinen" << "Sauce Bolognese" << "Sauce Hollandaise" << "Sauerkirschsaft" << "Sauerkraut" << "Sauerrahm" << "Schafskäse" << "Schalotten" <<
                             "Sauerkirschen" << "Schellfisch" << "Schinken roh geräuchert" << "Schinkenspeck" << "Schinkenwurst" << "Schlagsahne" << "Schmand" << "Schmelzkäse" << "Schnittlauch" << "Schokokuss" << "Schokoladeneis" << "Schokoladenpudding gekocht"
                             << "Schokomüsli" << "Schokoriegel" << "Scholle" << "Schupfnudeln" << "Schwarzbrot" << "Schwarze Bohnen" << "Schwarze Johannisbeeren" << "Schwarzer Johannisbeersaft" << "Schwarzwurzel" << "Schweinebauch" <<
                             "Schweinebraten" << "Schweinefilet" << "Schweinegulasch" << "Schweinehackfleisch" << "Schweinehaxe" << "Schweinekotelett" << "Schweineleber" << "Schweinerücken" << "Schweineschmalz" << "Schweineschnitzel paniert und gebraten"
                             << "Schweineschnitzel, roh" << "Schweineschulter" << "Schweinezunge" << "Schwertfisch" << "Seehecht" << "Seelachs" << "Seeteufel" << "Seezunge" << "Seitan" << "Sekt, halbtrocken" << "Sekt, trocken" << "Knollensellerie" <<
                             "Semmelknödel" << "Senf" << "Serrano Schinken" << "Sesam" << "Sesammehl" << "Sesamöl" << "Shiitake Pilze frisch" << "Skyr 0.2%" << "Softeis" << "Sojabohne" << "Sojaflocken" << "Sojajoghurt" << "Sojamehl" << "Sojamilch" <<
                             "Sojasauce" << "Sojasprossen" << "Sonnenblumenbrot" << "Sonnenblumenkerne" << "Sonnenblumenöl" << "Sorbit" << "Spaghetti Bolognese" << "Spaghetti gekocht" << "Spaghetti roh" << "Spare Ribs mariniert" << "Spargel" << "Spätzle"
                             << "Speck" << "Spezi Mezzo Mix" << "Spiegelei" << "Spinat" << "Spinat mit Rahm" << "Spitzkohl" << "Sprite" << "Stachelbeeren" << "Stangensellerie" << "Staudensellerie" << "Steckrüben" << "Steinpilze" << "Stevia" << "Stollen" <<
                             "Stremellachs" << "Stroh 80" << "Studentenfutter" << "Sülze Hausmacher Art" << "Suppenfleisch Rind" << "Suppenhuhn" << "Surimi" << "Sushi" << "Süßkartoffeln" << "Süßkirschen" << "Süßlupinenmehl" << "Süßstoff" << "Tabasco" <<
                             "Tafelspitz mager roh" << "Tahina Sesampaste" << "Tamarillo" << "Tamarinde" << "Tee schwarz" << "Teewurst" << "Thunfisch" << "Tilsiter Käse" << "Tintenfisch" << "Tiramisu" << "Toastbrot" << "Tofu" << "Tomate" << "Tomaten, getrocknet"
                             << "Tomaten, passiert" << "Tomatenmark" << "Tomatensaft" << "Tomatensauce" << "Tomatensuppe" << "Tonic Water" << "Topinambur" << "Tortellini" << "Tortenguss" << "Tortilla" << "Traubenkernöl" << "Traubensaft" <<
                             "Traubenzucker" << "Trinkschokolade" << "Trinkwasser" << "Trockenhefe" << "Trüffel" << "Tzatziki" << "Vanillepudding gekocht" << "Vanilleschote" << "Vanillezucker" << "Vollkornbrot" << "Vollkornbrötchen" <<
                             "Vollkornhaferflocken" << "Vollkornknäckebrot" << "Vollkornreis roh" << "Vollkorntoastbrot" << "Vollmilchschokolade" << "Wacholderbeeren" << "Walnüsse" << "Walnussmehl entölt" << "Walnussöl" << "Wassereis" << "Wassermelone" <<
                             "Weinbrand/Cognac (40%)" << "Weingeist/Sprit (95%)" << "Weinsauerkraut" << "Weinschorle" << "Weintrauben" << "Weißbier Weizenbier" << "Weißbrot" << "Weiße Bohnen roh" << "Weiße Schokolade" << "Weißkohl" << "Weißwein" <<
                             "Weißweinessig" << "Weißweinschorle" << "Weißwurst" << "Weizenbier alkoholfrei" << "Weizengras Pulver" << "Weizengrieß" << "Weizenkeimöl" << "Weizenkleie" << "Weizenknäckebrot" << "Weizenkorn" << "Weizenmehl 405" <<
                             "Weizenstärke" << "Weizenvollkornmehl" << "Welsfilet" << "Weltmeisterbrot" << "Whey Protein natur" << "Whisky (40% Vol.)" << "Wiener Schnitzel gebr." << "Wiener Würstchen" << "Wildente" << "Wildlachs" << "Wildreis gekocht" <<
                             "Wildreis gemischt roh" << "Wildreis roh" << "Wildschwein" << "Windbeutel" << "Wirsing" << "Wodka (40% Vol.)" << "Wurstsalat" << "Xylit" << "Zander" << "Zartbitterschokolade 50%" << "Zartbitterschokolade 75%" <<
                             "Zartbitterschokolade 85%" << "Zartbitterschokolade 90%" << "Ziegenfrischkäse" << "Ziegenkäse" << "Zimt" << "Zitrone" << "Zitronengras" << "Zitronensaft" << "Zucchini" << "Zucker" << "Zuckerrübensirup" << "Zuckerschoten" <<
                             "Zwieback" << "Zwiebel" << "Zwiebelkuchen" << "Zwiebelmettwurst";
                            ;
}
